# Generated by Django 5.2.6 on 2025-10-08 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playapp', '0002_remove_product_image_alter_product_description_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='customer_email',
            new_name='email',
        ),
    ]
